export default {
  asset: 'My Current Assets',
  title: 'Pool',
  performance: 'Performance',
  link: 'Link',
  rule: 'AVA Market Maker Investment Plan',
  tip: 'After donating to the pool, automatic compound interest of up to 1.2% daily based on donation amount, up to 30 days per donation.',
  tab1: 'Investment List',
  tab2: 'Redemption List',
  tab3: 'Buy List',
  confirmInviter: 'Confirm Inviter',
  address: 'Please enter inviter address',
  addAsset: 'Add Asset',
  inputIncreaseAmount: 'Please enter increase amount',
  option1: '1 day, 0.3% interest',
  option2: '15 days, 0.6% interest',
  option3: '30 days, 1.2% interest',
  selectDays: 'Please select days',
  cancel: 'Cancel',
  confirm: 'Confirm',
  index: 'Index',
  date: 'Date',
  principal: 'Capital',
  profit: 'Gain',
  action: 'Progress',
  pending: 'Pending',
  finished: 'Redeem',
  redeemed: 'Redeemed',
  success: 'Success',
  failed: 'Failed',
  numberError: 'Quantity Error',
  dayError: 'Day Error',
  noMore: 'No more',
};
