export default {
  asset: '내 현재 자산',
  title: '풀에 기부',
  performance: '실적',
  link: '링크',
  rule: 'I AVA 마켓 메이커 투자 규칙',
  tip: '풀에 기부 후 기부 금액에 따라 일일 최대 1.2% 자동 복리, 1회당 최대 30하늘.',
  tab1: '투자 목록',
  tab2: '상환 목록',
  tab3: '구입 목록',
  confirmInviter: '초대인 확인',
  address: '초대인 주소를 입력하세요',
  addAsset: '자산 추가',
  inputIncreaseAmount: '증가 금액을 입력하세요',
  option1: '1일, 복리 0.3%',
  option2: '15일, 복리 0.6%',
  option3: '30일, 복리 1.2%',
  selectDays: '일수를 선택하세요',
  cancel: '취소',
  confirm: '확인',
  index: '번호',
  date: '날짜',
  principal: '원금',
  profit: '수익',
  action: '상환 진행 상황',
  pending: '미도래',
  finished: '상환',
  redeemed: '상환완료',
  success: '성공',
  failed: '실패',
  numberError: '수량 오류',
  dayError: '일수 오류',
  noMore: '더 이상 없습니다'
};
