export default {
  asset: '我的当前资产',
  title: '捐赠底池',
  performance: '业绩',
  link: '链接',
  rule: 'I AVA做市商投资规则',
  tip: '捐赠底池后按捐赠额，每日最高1.2%自动复利，每次最高30天。',
  tab1: '投资列表',
  tab2: '赎回列表',
  tab3: '购买列表',
  confirmInviter: '确认邀请人',
  address: '请输入邀请人地址',
  addAsset: '增加资产',
  inputIncreaseAmount: '请输入增加金额',
  option1: '1天,复利0.3%',
  option2: '15天,复利0.6%',
  option3: '30天,复利1.2%',
  selectDays: '请选择天数',
  cancel: '取消',
  confirm: '确定',
  index: '序号',
  date: '日期',
  principal: '本金',
  profit: '盈利',
  action: '赎回进展',
  pending: '未到期',
  finished: '赎回',
  redeemed: '已赎回',
  success: '成功',
  failed: '失败',
  numberError: '数量错误',
  dayError: '天数错误',
  noMore: '没有更多了'
};
